shopware5/devdocs

source/index.html
* Fixed typo in "shopware"
* Fixed capital letters :point_up:
=> Fixed typos

source/designers-guide/theme-startup-guide/index.md
=> Typo in documentation

source/developers-guide/shopware-5-plugin-update-guide/index.md
Proof read existing content in the plugin upgrade guide
=> Proof read existing content in the plugin upgrade guide

source/assets/css/_imports/colors.less, source/assets/css/basic.css, source/assets/css/basic.less
Added style changes to provide a better overview.
=> devdocs style changes

source/sysadmins-guide/system-requirements/index.md
changed php_memory size from 128M to 256M
=> php_memory size

source/designers-guide/legacy-template-development-in-shopware-5/index.md
Added theme and template difference notice to legacy template development
=> Added theme/template difference notice

source/designers-guide/legacy-template-development-in-shopware-5/index.md, source/designers-guide/preparing-themes-for-the-community-store/index.md, source/designers-guide/smarty/index.md
=> Proof reading and typo fixes

source/designers-guide/javascript-statemanager-and-pluginbase/index.md
there was a syntax error in the if-statement
=> fix syntax error in if-statement

source/designers-guide/javascript-statemanager-and-pluginbase/index.md
=> Small typo fix

source/developers-guide/debugging/index.md, source/developers-guide/password-encoder/index.md
@dnoegel This affects two of your files, can you please make sure I didn't change your original intended message? thanks
=> Spellcheck debugging and password enconding docs

source/designers-guide/snippets/index.md, source/developers-guide/index.html, source/developers-guide/shopware-5-cli-commands/index.md
@arnoldstoba please review the rewritten version of the snippets document
=> Snippet rewrite and improvement

source/designers-guide/css-and-js-files-usage/index.md, source/designers-guide/css-file-usage/index.md, source/designers-guide/index.html
@klarstil would you please review the guide
=> Added JavaScript to "Using CSS files in themes" guide

source/designers-guide/snippets/index.md, source/developers-guide/shopware-5-cli-commands/index.md
=> Refactor CLI command article

source/designers-guide/snippets/index.md
Document the new showSnippetPlaceholder option.
Do not merge before the release of SW 5.0.2
=> 5.0.2 - Document snippet showSnippetPlaceholder option

source/blog/_posts/2015-07-23-cross-cutting.md
Cross cutting blog post review
=> Cross cutting blog post review

source/developers-guide/elasticsearch/index.md
Fixed some translation issues.
=> Correction for elastic search dev guide

source/designers-guide/theme-startup-guide/index.md
Because the missing semicolon you get an error if you try to open the theme settings
=> semicolon is missing

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
=> Upgrade guide for sw 5.1

source/developers-guide/index.html, source/developers-guide/shopware-5-media-service/index.md, source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
Add mediaservice guide
@janbuecker I reviewed your PR and did substantial changes to it. Please let me know what you think, and how do you think it compares to yours.
=> Add mediaservice guide

source/designers-guide/index.html, source/designers-guide/javascript-statemanager-and-pluginbase/index.md, source/designers-guide/managing-third-party-dependencies-with-bower/index.md, source/designers-guide/theme-startup-guide/index.md
@klarstil @tiagojsag Would you please review this guide really quick? :+1:
=> Add bower usage guide

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
Merge upgrade guide sections for 5.1 RC1 and RC2
=> Merge upgrade guide sections for 5.1 RC1 and RC2

source/designers-guide/snippets/index.md
=> Added namespace prefix notice

source/developers-guide/rest-api/examples/article/index.md, source/developers-guide/rest-api/examples/category/index.md, source/developers-guide/rest-api/examples/customer/index.md, source/developers-guide/rest-api/examples/order/index.md, source/developers-guide/rest-api/examples/translation/index.md
Fix links to api resources and client
=> Fix links to api resources and client

source/designers-guide/configuration-using-theme-php/index.md, source/designers-guide/custom-detail-page/index.md, source/designers-guide/custom-listing-page/index.md, source/designers-guide/custom-templates/index.md, source/designers-guide/edit-newsletter-and-document-templates/index.md, source/designers-guide/getting-started/index.md, source/designers-guide/javascript-statemanager-and-pluginbase/index.md, source/designers-guide/less/index.md, source/designers-guide/managing-third-party-dependencies-with-bower/index.md, source/designers-guide/smarty/index.md, source/designers-guide/theme-startup-guide/index.md, source/developers-guide/digital-publishing-elements/index.md, source/developers-guide/rest-api/models/index.md
=> Replace existing custom TOCs

.gitignore, app/config/sculpin_site.yml, app/config/sculpin_site_prod.yml, source/_layouts/default.twig.html
=> Disable google analytics for dev environment

source/developers-guide/lightweight-backend-modules/index.md
rename registerController() to registerBackendController() to prevent overwrite of Shopware_Components_Plugin_Bootstrap::registerController
use registerController() function instad of subscribeEvent()
=> change controller registration

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
Add TOC to upgrade guide + 5.1 section rename
=> Add TOC to upgrade guide + 5.1 section rename

source/developers-guide/backend-components/listing-extensions/index.md, source/developers-guide/index.html
Add missing link to batch processes BE component
=> Add missing link to batch processes BE component

source/blog/_posts/2015-10-14-graph-based-reco-engine.md
@dnoegel please review, thanks.
=> Correct spelling and links

source/developers-guide/shopware-5-media-service/index.md
* use an adverb instead of an adjective
* add a missing verb
=> grammar fix for two sentences

source/blog/_posts/2015-11-11-best-practice.md, source/blog/_posts/2015-11-11-best-practices.md
I would like to have this for wednesday next week if nothing is scheduled, yet? The request for some "best practice" guidelines is very common, so I decided to write this blog post.
I will proof-read it again later this day - but if you have any general remarks so far: let me know. 
@tiagojsag @bcremer
=> Add best practice blog post

source/designers-guide/find-smarty-blocks/index.md
Fixed typos and grammar, and rewrote parts of the guide for improved clarity and more natural language.
=> Partially rewrote "Finding Smarty blocks" guide

source/developers-guide/csrf-protection/index.md, source/developers-guide/index.html
SW-13107 - Added CSRF documentation
=> SW-13107 - Added CSRF documentation

source/designers-guide/javascript-statemanager-and-pluginbase/index.md
StateManager.registerEventListener is not a function.
StateManager.registerListener works
=> registerEventListener not a function

source/enterprise/tech-guide/installation-guide.md
=> Improve EDB shop host install docs

source/enterprise/tech-guide/installation-guide.md
Enterprise - Add MySQL user requirement on shop hosts
=> Enterprise - Add MySQL user requirement on shop hosts

source/assets/css/basic.less, source/assets/js/jquery.algolia.search.js
=> Add search hit highlighting

source/sysadmins-guide/varnish-setup/index.md
=> Varnish config proof reading

README.md, source/assets/css/basic.less, source/blog/_posts/2015-03-05-unboxing-myo-gesture-control-armband.md, source/blog/_posts/2015-05-04-unboxing-meta.md, source/blog/_posts/2015-08-11-seo-engine.md, source/blog/_posts/2015-10-07-what-is-an-item.md, source/blog/_posts/2015-10-14-graph-based-reco-engine.md, source/blog/_posts/2015-11-04-javascript-interfaces.md, source/blog/_posts/2015-11-18-dynamic-shopping-worlds.md, source/blog/_posts/2015-12-17-cv-testing.md, source/designers-guide/managing-third-party-dependencies-with-npm/index.md, source/designers-guide/range-slider-algorithm/index.md, source/developers-guide/backend-components/associations/index.md, source/developers-guide/backend-components/batch-processes/index.md, source/developers-guide/backend-components/detail/index.md, source/developers-guide/backend-components/listing-extensions/index.md, source/developers-guide/digital-publishing-elements/index.md, source/developers-guide/vagrant-phpstorm/index.md
@bcremer Here are the new image classes. I refactored all of our articles and added the documentation for the new classes to the README.md file
=> New image classes

source/enterprise/index.html, source/enterprise/tech-guide/installation-guide.md, source/enterprise/tech-guide/shopware-server-configuration-guide.md
Enterprise - EDB SW server config guide
=> Enterprise - EDB SW server config guide

source/developers-guide/lightweight-backend-modules-api/index.md
Had some struggle with it, so I thought it would be great to have it at the right place in the developer documentation. :smile:
=> Added examples for some detail views when using openModule(payload)

source/developers-guide/backend-components/batch-processes/index.md
=> typo fixed

source/developers-guide/event-guide/index.md
- fixed a syntax error in collect event example
- fixed spelling
- fixed missing module in example of the PostDispatch
=> fixed minor issues in the event guide

source/blog/_posts/2016-03-22-ecommerce-camp.md
Someone should tell @dnoegel that his talk will be in Berlin, not Hamburg ;)
=> Fix wrong location for codetalks

source/developers-guide/shopware-5-media-service/index.md
Added explanation to get thumbnail urls from media service
=> Update shopware5 media service index.md

source/enterprise/tech-guide/installation-guide.md, source/enterprise/tech-guide/shopware-server-configuration-guide.md
=> ENT-344 / ENT-463 / ENT-464 - update documentation and add a small howto

source/enterprise/tech-guide/shopware-server-configuration-guide.md, source/enterprise/user-guide/beta2/index.md
changes from the current sprint
=> Ent 495/update edb docs with configurable servers

source/developers-guide/address-management-guide/index.md, source/developers-guide/index.html
Someone should proof read this.
=> Add address management guide

source/sysadmins-guide/elasticsearch-setup/index.md
=> Document current Elasticsearch 2.0 requirenment

source/developers-guide/plugin-system/index.md
=> Fixed typo

source/developers-guide/plugin-system/index.md
=> update index.md with menu.xml

source/developers-guide/plugin-system/index.md
... with template and fixed headline of menu items
=> Added plugin controller registration

source/developers-guide/plugin-system/index.md
view here: https://developers.shopware.com/developers-guide/plugin-system/#register-plugin-controller-with-
=> fix documentation

source/developers-guide/rest-api/api-resource-generate-article-images/index.md
Adjusting the Access URL in the Table
=> Fix API path

source/blog/_posts/2016-09-05-psh-managing-build-complexity.md
Hey, hier schonmal der Text. Bitte einmal gegenlesen, danke!!!
=> ENT-569 - add psh blog post

source/designers-guide/html-smarty-coding-guidelines/index.md, source/developers-guide/coding-standards/index.md
A small guide about our HTML & Smarty coding guidelines.
@mitelg Would you be so kind and review the guide?
=> SW-16219 Add HTML / Smarty coding guidelines

source/developers-guide/custom-shopping-world-elements/index.md
Added manual for troubleshooting, when custom designer component is not working
=> Added troubleshooting manual (custom designer component)

source/developers-guide/rest-api/api-resource-address/index.md
=> Another Typo

source/sysadmins-guide/varnish-setup/index.md
=> Add known traps

source/_layouts/default.twig.html, source/assets/css/basic.less
- site navigation is now scrollable
- footer now fits to the site navigation
- removed unused footer styles
=> SW-16623 - Fix navi scrollbar and footer style

source/blog/_posts/2016-10-27-advanced-promise-patterns.md
New blog post scheduled for tomorrow morning
=> Add new blog post about advanced promise patterns

source/developers-guide/index.html, source/developers-guide/rest.html
=> sw-16552/add links for rest api endpoint article

source/developers-guide/csrf-protection/index.md
There may be problems with the httpOnly-Cookies, so I wrote a short description helping others with the same problem.
=> Problems with httpOnly-cookies

source/99-paper-cuts/index.md, source/blog/_posts/2016-10-12-promises.md, source/blog/_posts/2016-10-27-advanced-promise-patterns.md, source/contributing/contributing-code/index.md, source/contributing/index.html, source/developers-guide/backend-components/associations/index.md, source/developers-guide/plugin-system/index.md
found some typos and fixed them.
=> misc - fix some typos

source/developers-guide/rest-api/api-resource-address/index.md
=> Add customer to address resource

source/developers-guide/rest-api/index.md
Error messages from the server are now printed when the apiclient from the docs is used.
=> Improves demo API client to print error messages

source/developers-guide/rest-api/index.md
"To enables access…" should be "To enable access…"
=> Little typo fixed

source/developers-guide/address-management-guide/index.md
Da war noch eine ); hinter der schließenden }
=> Fixes broken example code

source/enterprise/tech-guide/shopware-server-configuration-guide.md
Typo and create .ssh directory
=> Typo and create .ssh directory

source/developers-guide/attribute-system/index.md
Kleines Beispiel wie Daten in Attribute persistiert und wieder ausgegeben werden können im Frontend.
=> Improves documentation for attribute usage in the frontend

exampleplugins/5.2/SwagShoeSize/Resources/views/frontend/account/index.tpl, exampleplugins/5.2/SwagShoeSize/Resources/views/frontend/register/personal_fieldset.tpl, exampleplugins/5.2/SwagShoeSize/SwagShoeSize.php, exampleplugins/5.2/SwagShoeSize/plugin.xml, source/developers-guide/attribute-system/index.md
Source for attribute usage example added
=> Adds example plugin "SwagShoeSize"

exampleplugins/legacy/Frontend/SwagCustomRiskRule/Bootstrap.php
Fix for https://github.com/shopware/devdocs/issues/458
=> Fix risk rule namespace

source/blog/_posts/2015-05-05-never-stop-refactoring.md
Hi there,
just some typo fixes.
=> Fixes small typos

source/developers-guide/plugin-extension-by-plugin/index.md
This update fixes a hand full of typos throughout the content and the edit link shown in the top right.
=> Typos fixed

source/developers-guide/event-guide/index.md
Fixes some minor typos and grammar things.
=> Typos and grammar

exampleplugins/5.2/SwagBannerApi/plugin.xml, exampleplugins/5.2/SwagLastRegistrationsWidget/plugin.xml, exampleplugins/5.2/SwagPaymentExample/plugin.xml, exampleplugins/5.2/SwagShoeSize/plugin.xml, exampleplugins/5.2/SwagTestExample/plugin.xml, source/developers-guide/plugin-lastregistrations-widget/index.md, source/developers-guide/plugin-system/index.md
Follow up from: https://github.com/shopware/devdocs/pull/479
=> misc - unify schema locations

source/designers-guide/index.html
Fixes a little typo: "an outdated" instead of "a outdated"
=> Fixed a little typo

source/designers-guide/custom-detail-page/index.md
Deletes the 2nd <div class="toc-list"></div> in text.
=> Delete 2nd TOC from content

source/designers-guide/custom-listing-page/index.md
Fixes: "through" instead of "though"
=> Fixes a small typo

source/developers-guide/plugin-system/index.md
https://github.com/shopware/shopware/pull/939
=> Added doc for type button along to PR in shopware

source/developers-guide/csrf-protection/index.md
Added some guidelines for loading data using ajax while preventing CSRF errors.
=> Add some best practices for loading Ajax data to prevent CSRF errors

exampleplugins/5.2/SwagCustomSlugConfig/Resources/services.xml, exampleplugins/5.2/SwagCustomSlugConfig/SwagCustomSlugConfig.php, exampleplugins/5.2/SwagCustomSlugService/Resources/services.xml, exampleplugins/5.2/SwagCustomSlugService/SlugService.php, exampleplugins/5.2/SwagCustomSlugService/SwagCustomSlugService.php, source/developers-guide/plugin-slugify/index.md
Extracted from shopware/shopware#1001
=> Document slugify

source/developers-guide/rest-api/api-resource-shops/index.md
rest-api shops endpoint POST/PUT updated with correct minimum required params
=> update rest-api shop POST/PUT with correct params

source/blog/_posts/2017-02-06-javascript-currency-formatting.md, source/designers-guide/getting-started/index.md, source/sysadmins-guide/system-requirements/index.md
Used correct verb forms of _recommend_.
=> grammar (to recommend)

exampleplugins/5.2/SwagExtendArticleResource/Components/Api/Resource/Article.php, exampleplugins/5.2/SwagExtendArticleResource/Resources/services.xml, exampleplugins/5.2/SwagExtendArticleResource/SwagExtendArticleResource.php, exampleplugins/5.2/SwagExtendArticleResource/plugin.xml, source/developers-guide/rest-api/extend-api-resource/index.md, source/developers-guide/rest.html
=> Extend article resource article and example plugin

source/developers-guide/rest-api/api-resource-media/index.md
Changed the described type for the "changed" field from date/time to date.
It's a "date" field in the database.
=> Updated the type of the "changed" field

source/developers-guide/rest-api/examples/article/index.md
This attribute is needed for the article to be available. https://forum.shopware.com/discussion/comment/192651
=> Add `active` attribute to mainDetail section

source/sysadmins-guide/varnish-setup/index.md
@dnoegel @bcremer Some improvements for special cases
=> Fix some varnish issues

source/designers-guide/eslint-for-plugins/index.md
=> SW-18384 Added guide on how to use eslint in shopware plugins

exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Bootstrap.php, exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Components/YouTubeHandler.php, exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Subscriber/ElementHandler.php, exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Subscriber/Resources.php, exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Views/backend/swag_digital_publishing_sample/view/editor/elements/youtube_element_handler.js, exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Views/backend/swag_digital_publishing_sample/view/editor/extension.js, exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Views/frontend/_public/src/less/all.less, exampleplugins/legacy/Backend/SwagDigitalPublishingSample120/Views/widgets/swag_digital_publishing/components/youtube.tpl, source/developers-guide/digital-publishing-elements/index.md
Updated the "Digital Publishing Elements" guide due to plugin changes
=> Update digipub elements guide

source/developers-guide/backend-components/listing/index.md
Per https://forum.shopware.com/discussion/46503/plugin-unable-to-load-template-part-3
Just to make sure nobody else will run into this issue :)
=> Improve documentation on undocumented behaviour

source/developers-guide/rest-api/api-resource-orders/index.md
PUT request section should describe orders endpoint and parameters.
=> Fix typo in PUT method

exampleplugins/5.2/SwagReCaptcha/Resources/services.xml, source/developers-guide/dic-tags/index.md, source/developers-guide/implementing-your-own-captcha/index.md
This page will give you an overview of all available container tags to extend Shopware.
=> Document Shopware DIC tags

app/SculpinKernel.php, app/src/GitHistoryBundle/DependencyInjection/SculpinGitHistoryExtension.php, app/src/GitHistoryBundle/HistoryListener.php, app/src/GitHistoryBundle/Resources/config/services.xml, app/src/GitHistoryBundle/SculpinGitHistoryBundle.php, source/index.html
This PR adds a latest changes section to the front page to indicate which articles have been edited recently.
=> SW-18720 - Add documentation history

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
Guess the "Other changes" part has to be filtered out.
=> Upgrade guide 5.2.x - 5.3.0

source/developers-guide/shopware-config/index.md
=> catched -> caught

source/developers-guide/rest-api/api-resource-address/index.md
You need to specifiy the missing field customer to post a new address.
-- Added customer (integer -> foreign key)
=> Missing Field for posting a new address

source/developers-guide/backend-components/basics/index.md
=> Fixed code typo in backend-components/basics

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
- cab -> may be
- altered some "can" to "may"
=> styling changes.

source/designers-guide/javascript-statemanager-and-pluginbase/index.md
Hopefully, I didn't miss anything 🙏
I'll do a few more of these in the future if you guys like these kind of PR's, there are many many many style issues in the English devdocs 🤔
=> Fix style & grammar issues on the StateManager/Plugin page

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
previous url led to a 404 page
=> fixed broken link "5.3 signature"

source/developers-guide/plugin-system/index.md
see https://github.com/shopware/shopware/blob/5.4/UPGRADE-5.2.md#5213
=> 5.2 plugin system: added frontend resources auto-registration

source/developers-guide/plugin-extension-by-plugin/index.md
=> Fix dead link for example plugin download

source/developers-guide/rest-api/customer-streams/index.md
Update customer stream dev docs to match the current implementation.
=> Update Customer Stream REST API documentation

source/developers-guide/plugin-system/index.md
added reading scoped configuration, change to cached config service for performance
=> updated config reading new plugin system

source/sysadmins-guide/varnish-setup/index.md
This should be reviewed and tested further to verify it really works. I've done some basic tests and they've worked.
=> Update varnish configuration to support custom stream features

source/developers-guide/rest-api/api-resource-orders/index.md
Get (List)-operation for orders was missing --> Added.
=> Added missing Get (List)-operation for orders

source/developers-guide/custom-shopping-world-elements/index.md
This extra information about the subscriber registration was missing here.
=> Extend custom emotion element article

source/developers-guide/rest-api/api-resource-orders/index.md
Link to Payment model was set to payment-instance -> fixed it.
=> [REST-API] Updated link to Payment model

source/designers-guide/general-resources.html, source/designers-guide/index.html
If pull request https://github.com/shopware/devdocs/pull/389 will be declined due to duplicate content I made this one.
It's easier to find the icon set and link will be added to search machine index.
=> [FEATURE] Added direct link to icon set

source/developers-guide/rest-api/examples/article/index.md
Add an example which shows how to update the SEO categories of a product via REST API
=> Add a REST API example for updating the SEO categories of a product

source/sysadmins-guide/sessions/index.md
Fix memcache/memcached Naming (since you explain how to use and install memcached, not memcache)
=> Fix memcache/memcached Naming

source/developers-guide/custom-shopping-world-elements/index.md
In response to this board issue: https://forum.shopware.com/discussion/49908/einkaufswelt-erweiterung-sauber-deinstallieren
Maybe there a mistake in daniel's book.
=> clarify emotion element deinstallation

source/sysadmins-guide/shopware-cluster-setup/index.md
Typos I noticed while reading.
=> Typo fixes

source/developers-guide/product-export/index.md
small information on how to modify the output of product exports with a plugin
=> extending product export

source/developers-guide/shopware-5-core-service-extensions/index.md
Adjusted documentation for core service extension via plugin to fit the new plugin system.
=> Migrate core service extension documentation

source/developers-guide/rest-api/examples/article/index.md, source/developers-guide/rest-api/examples/media/index.md
Adding info to article/media API for easier understanding that file is an option to use images on the server
=>  Article images API complement

source/developers-guide/plugin-system/index.md
Add more information and examples on how to use the contexts in bootstrap class.
=> add more detailed information on bootstrap contexts

source/developers-guide/lightweight-backend-modules/index.md
Replaced wrong function name in text with correct one from the working example.
=> Fixed lightweight backend modules index.md

exampleplugins/5.2/SwagVimeoElement/Subscriber/TemplateRegistration.php, source/developers-guide/custom-shopping-world-elements/index.md
the registration of the emotion component view subscriber was missing and a duplicate of the subscriber for the backend extension was mixed in between the description of the emotion handler
=> fixed vimeo element example

source/designers-guide/javascript-statemanager-and-pluginbase/index.md
Added attributes and example for applyDataAttributes() method.
=> Deliver more info about applyDataAttributes()

source/_layouts/start.twig.html, source/assets/css/basic.less, source/designers-guide/index.html
add a Link to the new style tile page 
change wording Styleguide in Style tile
=> add style tile link - edit wording style tile

source/developers-guide/general-resources.html
We started with the community to create a awesome-shopware list on github. I would like link it on general resources. ❤️
=> Added awesome-shopware list

source/designers-guide/find-smarty-blocks/index.md
one duplicate folder in the directory structure. was "documents", should be "widgets"
=> Fix directory structure overview

source/developers-guide/shopware-config/index.md
Changes according to https://github.com/shopware/shopware/blob/5.3/engine/Shopware/Configs/Default.php#L110
=> fix typo in config

source/developers-guide/shopware-5-performance-for-devs/index.md, source/developers-guide/shopware-5-search-bundle/index.md, source/sysadmins-guide/shopware-cluster-setup/index.md
=> less -> fewer

source/developers-guide/plugin-quick-start/index.md
=> proper cronjob description

source/developers-guide/attribute-system/index.md
For Ext.form.field.Text from 5.3.0
=> Fixed Unified type VARCHAR to TEXT

source/designers-guide/configuration-using-theme-php/index.md, source/designers-guide/css-and-js-files-usage/index.md, source/designers-guide/theme-startup-guide/index.md
Please do not merge before Shopware 5.4 is released!
=> Add documentation about the Less/JS discard feature in Shopware 5.4

source/developers-guide/general-resources.html, source/developers-guide/index.html, source/developers-guide/shopware-composer/index.md
Please check if you understand everything and the content is fitting.
=> Added composer documentation

source/designers-guide/best-practice-theme-development/index.md
Fixes https://github.com/shopware/devdocs/issues/786
=> Change node.js installation instructions

source/developers-guide/debugging/index.md, source/developers-guide/general-resources.html, source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md, source/developers-guide/shopware-composer/index.md
(and fix some link order issues)
=> Add variants, laststock to upgrade guide

source/assets/css/basic.less
This was a failure change - so i change it back.
=> hide scrollbar in main navigation

source/sysadmins-guide/sessions/index.md
We had some issues with this. Just to let others know.
=> add prefixes to redis session config

index.html
=> Fix wording on frontpage of the styletile

source/developers-guide/debugging/index.md
I have migrated the Profiler repository to Friends of Shopware repository.
=> Updated link to Profiler

source/designers-guide/configuration-using-theme-php/index.md
Seems like I added a typo while fixing typos. Nice one :D
=> Fix another typo

source/sysadmins-guide/system-requirements/index.md
I added a little bit of documentation for SW-19096, SW-19639
=> Add MySQL parameters

source/designers-guide/best-practice-theme-development/index.md
Without = the Error
>> Error: Unable to read "../web/cache/config_true.json" file (Error code: ENOENT).
occurs.
@mitelg I created a new branch. Btw. is it somehow possible to watch all shops? If not maybe a short info would help:
`grunt` #This will watch the shop with ID 1
=> Fix grunt call with equal sign

source/developers-guide/index.html
Currently it shows incorrect on windows
=> Removed unknown symbol

source/sysadmins-guide/elasticsearch-setup/index.md, source/sysadmins-guide/index.html, source/sysadmins-guide/professional-deployments/index.md, source/sysadmins-guide/sessions/index.md, source/sysadmins-guide/shopware-5-performance-for-sysadmins/index.md, source/sysadmins-guide/shopware-cluster-setup/index.md, source/sysadmins-guide/varnish-setup/index.md
This will still miss a lot of stuff, be kind. :)
=> Professional deployment article

source/blog/_posts/2017-11-17-on-testing-strategies.md
=> Fix for issue #768

source/developers-guide/index.html, source/sysadmins-guide/professional-deployments/index.md
The link wasn't rendered properly
=> Fixes link in professional deployments

exampleplugins/5.2/SwagExtendCustomer/Resources/views/backend/swag_extend_customer/view/detail/window.js
There was a bug in 5.4 for me. Now it seems to work.
=> Fix bug in SwagExtendCustomer plugin

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
the provided example has a syntax error
=> fixed garbage collector example

source/developers-guide/rest-api/api-resource-property-group/index.md
=> Change field name for "sortmode"

source/developers-guide/rest-api/examples/category/index.md
=> Fixed bracket-typo

source/developers-guide/rest-api/examples/category/index.md
There are multiple quote types which lead to invalid code snippets
And an other bracket typo
=> Fixed multiple quote typos

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
Please read once and check in particular if the topics you yourself worked on are described correctly.
=> Add Upgrade guide for 5.5

source/designers-guide/edit-newsletter-and-document-templates/index.md
The directory structure is wrong, since the document folder is a subfolder of the Bare theme and not the responsive theme.
=> change directory structure

source/sysadmins-guide/installation-guide/index.md
Updated the README.md link to use 5.5 rather than 5.3
=> Update link to README.md

source/developers-guide/rest-api/api-resource-manufacturers/index.md
This PR should only be merged after Ticket SW-21306 (allow to remove an suppliers image via api) has been merged successfully.
=> Add examples for manufacturer requests

source/developers-guide/rest-api/api-resource-categories/index.md
Updated the available fields for categories' POST and PUT requests and added an example for a POST request
=> Updated POST and PUT for categories

source/developers-guide/shopware-5-cli-commands/index.md
=> Fix Command registration Documentation

source/developers-guide/rest-api/models/index.md
Should only be merged when PR https://github.com/shopware/shopware/pull/1261 has been merged successfully
=> Add Esd and EsdSerial to model

source/developers-guide/shopware-config/index.md
I added documentation for the environment specific config.php
=> Add environment-specific config.php documentation

source/developers-guide/shopware-composer/index.md
Updated the path of the install.sh like it is on https://github.com/shopware/composer-project#installation
=> Change path of install.sh

source/developers-guide/vagrant-phpstorm/index.md
https://github.com/shopwareLabs/shopware-vagrant/blob/master/Vagrantfile#L9
Its 16.04 :)
=> Update vagrantbox ubuntu version

exampleplugins/5.2/SwagExtendCustomer/Resources/views/backend/swag_extend_customer/controller/my_own_controller.js, exampleplugins/5.2/SwagExtendCustomer/Resources/views/backend/swag_extend_customer/view/detail/my_own_tab.js, exampleplugins/5.2/SwagExtendCustomer/Resources/views/backend/swag_extend_customer/view/detail/window.js, source/developers-guide/backend-extension/index.md
Missing empty lines has broke the extjs template (cutting code)
titleCombobox has not worked, he couldn't find the element. I use a different method which looks also better :wink:
=> Fix backend extension tutorial

source/developers-guide/attribute-system/index.md
Should only be merged if https://github.com/shopware/shopware/pull/1568 has been merged successfully.
=> Add documentation for setting an attribute's default value

source/sysadmins-guide/elasticsearch-setup/index.md
Add the documentation for the new elasticsearch version config.
=> NTR - add elasticsearch version

source/sysadmins-guide/varnish-setup/index.md
Its the same part as here https://github.com/shopware/shopware/commit/9678d330f41bcb71a649a450d5adbcdc102581ba#diff-33b203a54a279f0f62165b2e3fc6fe1cR365 for Varnish setups
it can be merged, cause it breaks nothing
=> HTTP2 Push compatibility

source/developers-guide/shopware-config/index.md
This PR should only be merged after SW-22082 has been merged successfully.
=> Add possible options for elasticsearch

source/designers-guide/best-practice-theme-development/index.md
Added example for grunt tast development.
=> Added grunt development example

source/blog/_posts/2015-09-01-plugin-generation.md
fix for the wrong haveFilters option to haveFilter
=> fix command typo in blog post

source/designers-guide/datepicker/index.md
related to https://issues.shopware.com/issues/SW-23390 ? :-)
=> adjust placeholder to show usage snippets

source/assets/css/basic.less
FYI: @ndzoesch
- updated the "back to shopware" button on offcanvas menu
=> changed button on offcanvas

iframe/icon-set.html
there are many wrong naming in icon-set.html
=> correct naming

source/developers-guide/backend-components/associations/index.md
=> change integer to boolean

source/developers-guide/cheat-sheet/index.md
A little case from the dev-support
=> Add attribute loading to cheatsheet

source/developers-guide/content-types/index.md, source/developers-guide/general-resources.html
=> SW-23700 - Add content type documentation

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
=> Add Upgrade Guide for Shopware 5.6

source/sysadmins-guide/elasticsearch-setup/index.md
See the original key: https://github.com/shopware/shopware/blob/354cb81eb3ed11b6cad8e2861aefc4a3796c1e9f/engine/Shopware/Configs/Default.php#L157
=> Amend configuration key

source/developers-guide/plugin-configuration/index.md
Updated the documentation for remote combobox
See forum thread here:
https://forum.shopware.com/discussion/comment/250145#Comment_250145
=> Update documentation for remote combobox

source/developers-guide/plugin-testing/index.md
The path to the TestCase Class on line 60 has been updated.
Fixed an typo on line 49.
=> Updated path to TestCase and fixed typo

source/developers-guide/rest-api/api-resource-user/index.md
change http method to post and use a more common roleId
=> wrong http method

source/sysadmins-guide/system-requirements/index.md
Fix the link to the Elasticsearch setup
=> Fix ES link

source/sysadmins-guide/sessions/index.md
Update the package name for memcache, unify array syntax
=> Unify array syntax, update memcache package

source/developers-guide/rest-api/models/index.md
The documentation and the given result of an order request differs so i fixed in this part the order billing models
=> Fix Order Billing Model

source/developers-guide/rest-api/models/index.md
The documentation and the given result of an order request differs so i fixed in this part the order shipping models
=> Fix Order Shipping Model

source/developers-guide/rest-api/models/index.md
The previous model doesn't exist so fixed this to the correct one.
=> Fix document type model

source/developers-guide/rest-api/models/index.md
I removed alwaysSecure as this got removed entirely in shopware.
=> Remove shop alwaysSecure

source/sysadmins-guide/sessions/index.md
File is not a valid session handler on cli
PHP Warning:  ini_set(): Cannot find save handler 'file' in /var/www/html/shopware/engine/Library/Zend/Session.php on line 213
=> Remove file example

source/developers-guide/rest-api/examples/category/index.md
Fix examples :)
```
Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/shopware/engine/Shopware/Components/Model/CategorySubscriber.php:296
```
=> Add missing required parentId

source/developers-guide/cookie-consent-manager/index.md, source/developers-guide/general-resources.html
Added guide for the new cookie consent manager
=> SW-24691 - Add cookie consent guide

source/_layouts/default.twig.html, source/_partials/api_badge.twig, source/assets/css/_imports/api-badge.less, source/assets/js/jquery.api-badge-copy-button.js, source/developers-guide/rest-api/index.md
This PR adds a button to copy the request body to all API example-badges, as suggested by @shyim :wink:
=> NTR - Add a button to copy the request body to all api-badges

source/developers-guide/cheat-sheet/index.md
Sort of part of https://github.com/shopware/devdocs/pull/1058 but changes more delicate parts of the documentation
=> Add shortcut on cheat sheet to command completion

source/developers-guide/shopware-config/index.md
=> added media whitelist

source/developers-guide/event-guide/index.md
The current one looks very strange :see_no_evil:
=> Simplify notifyUntil example

README.md
To make the Codeblocks more Readable :).
=> Add Syntax to Codeblocks

source/blog/_posts/2015-11-11-best-practices.md, source/developers-guide/plugin-quick-start/index.md
Signed-off-by: Jelle Deneweth <jelle.deneweth@gmail.com>
=> Fix typo's in documentation

source/developers-guide/content-types/index.md
Added info on how to update the configuration without having to reinstall a plugin
=> Update content-types docs

source/developers-guide/plugin-quick-start/index.md
cache and logs folder are both inside "var"
=> fix location of cache and logs folder

source/developers-guide/rest-api/api-resource-customer/index.md, source/developers-guide/rest-api/models/index.md
fixes https://github.com/shopware/devdocs/issues/805
=> Add comment for customer property firstLogin

source/developers-guide/plugin-quick-start/index.md, source/developers-guide/shopware-5-cli-commands/index.md
fixes https://github.com/shopware/devdocs/issues/1092
=> Fix method name in text description of code example

source/sysadmins-guide/system-requirements/index.md
fixes https://github.com/shopware/devdocs/issues/1064
=> Document MySQL transaction isolation level

source/developers-guide/debugging/index.md
fixes https://github.com/shopware/devdocs/issues/1074
=> Fix debugging article about ExtJs

source/sysadmins-guide/system-requirements/index.md
Forgot to add a newline yesterday, now the List is not separated from the following paragraph anymore.
=> Separate sections visually
