source/designers-guide/theme-startup-guide/index.md
The createTextField-function does not accept an array. The correct way is to enter the strings directly as parameters.
=> Fix: Error in createTextField()-function

source/designers-guide/theme-startup-guide/index.md
According to the unitize.less the documented way of using the unitize mixin is deprecated. Updated it to the new one.
Actually I don't know wether it is necessary to mention the base value of 16 here. Wouldn't it be better if there was an additional paragraph about the @remScaleFactor and how to change that if necessary?
=> Update documentation for unitize mixin

source/designers-guide/index.html, source/designers-guide/modify-jquery-plugins/index.md
Here's a new guide about overriding our default jQuery plugins with the new ```$.overridePlugin``` method in Shopware 5.0.2
@tiagojsag Would you be so kind to check the grammar and spelling? Thanks in advance!
=> Added a guide about modifying jquery plugins

source/developers-guide/index.html
I suggest to remove the tutorial section again - guides like this have been added to the "plugin resources" before - if we want to have a "tutorial" section, we should still move the existing "tutorial-like" guides to there - e.g. store front components, password encoder, plugin quick start.
=> Remove tutorial section

source/designers-guide/best-practice-theme-development/index.md
users should never edit/create files in /usr/bin, and nodejs-legacy package provides node symlink. (and also depends on nodejs)
=> use nodejs-legacy on ubuntu

README.md, source/_layouts/default.twig.html, source/assets/js/jquery.toc.js
Added a jQuery plugin which generates a ToC list on fly. To use it, just place a element with the class `toc-list` in your markdown document.
If the element is a unordered list (`ul`) or ordered list (`ol`), the plugin will generated a nested list. If you use a `div` element, the plugin will generate a list of anchor elements.
*Example:*
```
<ul class="toc-list"></ul>
```
=> SW-12794 Added: Plugin which generates a toc list on the fly

source/developers-guide/backend-components/basics/index.md, source/developers-guide/lightweight-backend-modules/index.md
Installing a plugin with the 2-parameter-call results in an `E_RECOVERABLE_ERROR`. We should provide an key/value array.
=> Fixed PHP7 compatibility

README.md, source/_layouts/default.twig.html
I think that it is neccessary to provide developers with a version history of a document.
**Example: CSRF Protection**
Currently, the article describes how the protection works in general and how it has been implemented in the backend. 
What if we document the frontend implementation or do changes to the current backend implementation? How does a developer know, when and what has changed since he last visited this article?
For that reason, i've implemented a new meta tag called `history`. It's a simple key/value array whereas the key is the date of change, syntax `yyyy-mm-dd`, and the value is a short summary of the changes. So the meta tag could be used like this:
```
history:
2015-11-16: creation
2015-11-23: added frontend documentation
2016-01-01: documented millenium bug
``` 
This …
=> Added version history for articles

source/developers-guide/rest-api/index.md
in some server configurations the web server rejects http requests without an http user agent. Some kind of annoying troubleshooting why it works with a BrowserRequest but not with an php script ;-)
=> adding http_user_agent to curl request

source/developers-guide/lightweight-backend-modules/index.md
Added a small section which links to the newly published demo plugin for the lightweight backend modules.
=> Added demo plugin for the lightweight backend modules guide

source/designers-guide/configuration-using-theme-php/index.md
If the **;** is not set, the theme configuration does not load.
=> fixed semicolon

source/developers-guide/shopware-5-media-service/index.md
replaced href attribute with src attribute to create a working image example ;-)
=> Fix typo in smarty media plugin example

source/developers-guide/rest-api/api-resource-translation/index.md
Since Shopware 5.0.0 the translation api expects a shopId (instead of a localeId) ..
=> Fixed translations api doc

.gitignore, composer.json, composer.lock, source/_layouts/default.twig.html, source/designers-guide/custom-listing-page/index.md, source/designers-guide/find-smarty-blocks/index.md, source/designers-guide/responsive-images/index.md, source/developers-guide/shopware-5-media-service/index.md, source/developers-guide/shopware-5-plugin-update-guide/index.md
This PR replaces the packaged highlight.js with the current one using a CDN. Because there is a custom smarty parser, the code have been changed to html.
=> Updated highlight.js

source/assets/css/_imports/codeExpand.less, source/assets/css/basic.less, source/developers-guide/address-management-guide/index.md
This is just a styling update which, in my opinion, is more readable and makes an cleaner look overall. This is only related to `<code>` blocks.
I've removed the border, increased the padding and modified the expand button to fit the code styling.
=> Make the styling of code simpler

source/designers-guide/snippets/index.md
=> Typo in documentation

source/developers-guide/rest-api/examples/article/index.md, source/developers-guide/rest-api/examples/category/index.md, source/developers-guide/rest-api/examples/customer/index.md, source/developers-guide/rest-api/examples/order/index.md, source/developers-guide/rest-api/examples/translation/index.md
This fixes link on pages like https://developers.shopware.com/developers-guide/rest-api/examples/order/
=> Fix links from API example pages to corresponding resource pages.

source/assets/js/app.js
The debug mode was still active which has the effect that the auto complete result will not be closed when the user clicks outside of the pop in.
=> Disable debug mode

source/assets/css/_imports/overlay.less, source/assets/css/basic.less, source/assets/js/app.js
The user can easily lose the focus and don't realise the search result is already rendered. Using an overlay we get a much better focus on the actual search result.
Check out the preview to get an idea how it will look like:
=> Add overlay for search result

source/developers-guide/controller/index.md
The example namespaces for controllers were singular but need to be in plural form. This PR fixes this.
Have fun
Hendrik
=> Fixed paths in controller namespaces

source/developers-guide/plugin-system/index.md
Shopware `> 5.2.7` automatically registers controllers, I think it should be documented :)
Further I removed invalid XML-comments which lead to copy-paste errors and added another example plugin.
=> Add automatic controller registration documentation

source/developers-guide/rest-api/examples/article/index.md
from https://developers.shopware.com/developers-guide/rest-api/examples/api-resource-property-group
to https://developers.shopware.com/developers-guide/rest-api/api-resource-property-group/
=> Fixed some typos | Broken Links

source/designers-guide/how-to-use-karma/index.md
The new version of Karma is using a new version of the test framework `jasmine` which got splitted up in the `karma-jasmine` test runner and the actual framework `jasmine-core`. This PR updates the dependencies in the corresponding guide.
=> Correct dependencies for Karma

source/developers-guide/rest-api/index.md
Fixes a warning when the key 'errors' does not exist in the array $decodedResult
=> Improve error handling of example API client

source/sysadmins-guide/sessions/index.md
Explains a workaround for long running ajax requests
=> Explain possible workaround for session locking

source/designers-guide/javascript-coding-style/index.md
Example for "comma spacing" lacked a semicolon. Added it.
=> Add semicolon to example

source/developers-guide/phpstorm/index.md
Include directory "var/cache/production_DATE/doctrine" to allow PhpStorm to autocomplete getter and setter of attributes. E.g. $article->getAttribute()->getAttr4()
Otherwise PHPStorm is not able to autocomplete these functions
=> "exclude from exclude" directory var/cache/production_DATE/doctrine

source/developers-guide/backend-components/batch-processes/index.md
The proper name of the plugin SwagProductAssociation is SwagProductAssoc.
See: https://github.com/shopware/devdocs/tree/master/exampleplugins/legacy/Backend/SwagProductAssoc
=> Name and link to example plugin broken

source/developers-guide/plugin-system/index.md
I think using the container parameter is better than getting the plugin and invoking getPath on it. What do you think?
=> Fetching plugin-path from service parameter

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
Basically, I just moved some blocks around and added a new section about SSL.
> ### SSL Encryption
>
> The mixed SSL encryption mode in the shop configuration has been deprecated in 5.3 in favour of a stronger security policy. As of 5.4, the SSL encryption can only be enabled or disabled globally.
=> SW-19205 - Announce deprecation of SSL mixed mode

source/sysadmins-guide/elasticsearch-setup/index.md
when you copy&paste it to your existing config.php, the first array cling square causes problems and the settings will not be used. the view should be better with an example config.php
=> Improve config settings of elasticsearch

source/developers-guide/customer-streams-extension/index.md
Link is broken and results in 404, set direct link to correct page.
=> Fix broken link to customer streams api

source/developers-guide/rest-api/faq/index.md, source/developers-guide/rest-api/index.md
Extended the API basic section and the faq with documentation about the HTTP Basic auth which will be introduced with Shopware 5.3.2
=> Add documentation about HTTP basic auth support

source/developers-guide/global-variables-in-templates/index.md
Rename variable in order to prevent confusion due to inconsistent naming:
`sUserLoggedIn` misleadingly spelled `sUserloggedIn`.
=> Fix variable case in naming

source/developers-guide/rest-api/api-resource-address/index.md, watch.sh
The warning is regarding when an API user tries to assign address to another customer
=> SW-19708 - Add warning for REST API docs

source/developers-guide/rest-api/api-resource-categories/index.md
Fixed schema for GET operation. The parameter 'external' is a string instead of a boolean.
=> [REST-API] Fixed GET schema for category

source/developers-guide/rest-api/models/index.md
When getting a specific Order, you also get a Payment-model.
This model was missing, so I added it ;).
=> Added missing model for Order resource (Payment)

source/developers-guide/rest-api/api-resource-orders/index.md
The appearance of the table in the order's model was screwed up.
The problem was only visible when switching from soft-wrap to no-wrap.
=> [REST-API] Fixed a little optical issue

source/designers-guide/snippets/index.md
This small update should help to avoid misunderstandings in placing .ini files and using the correct namespaces in individual themes.
=> Update of description for .ini usage

source/developers-guide/plugin-quick-start/index.md
As this guide covers plugin development in Shopware versions not older than version 5.2, the Shopware 4 template structure is irrelevant.
=> Fixed typo and removed mentions about Shopware 4

source/developers-guide/models/index.md
Most apparent change is that I replaced the Type annotations for the entity-manager from `Doctrine\ORM\EntityManager` to `Shopware\Components\Model\ModelManager` after noticing, that I am working with a `ModelManager` when I wrote an event listener. While `EntityManager` is technically correct and sufficient in most cases, I imagine it's still good to know that there is more than that.
Additionally, there are a couple of minor changes regarding code-style.
Merry Christmas 🎄  :skier:
=> Few changes in Models documentation

source/developers-guide/shopware-config/index.md
Since SW-20299 it is possible to use a redis-auth, but if this parameter isn't set, the implementation won't work.
=> Fix-missing-redisAuth-parameter

source/developers-guide/debugging/index.md
The fourth argument must be false, so dump returns the result
=> Fixed debug usage

source/developers-guide/shopware-5-search-bundle/index.md
There is no README.md in Shopware\Bundle\StoreFrontBundle, I think it should be Shopware\Bundle\SearchBundle\README.md
=> fix readme notice in searchbundle

source/developers-guide/shopware-5-upgrade-guide-for-developers/index.md
The SEO routes got scraped, so we need to remove them from the upgrade guide
=> Remove checkout SEO description

source/designers-guide/snippets/index.md
The current documentation only specifies the location of snippet .ini files for themes.
This commit adds information on where to place snippet .ini files for plugins.
=> Added note for snippet placement in plugins.

source/designers-guide/configuration-using-theme-php/index.md
The classname was wrong. Also fixed some typos and optimized the wording.
=> Fix Typos and Classname for discarding JS/CSS

source/developers-guide/shopware-config/index.md
The examples above use "[]" instead of "array()", should be consistent.
=> Changed array notation

source/designers-guide/snippets/index.md
As seen in the [snippet manager code](https://github.com/shopware/shopware/blob/5.4/engine/Shopware/Components/Snippet/Manager.php#L310) the actual namespace starts with `themes/` instead of `theme/`.
=> Correct typo: snippet namespace missed one character

source/designers-guide/index.html
Links to style tile now lead to `/styletile/` instead of `http://styletile.dev.shopware.in/`
=> Fixed style tile link

source/developers-guide/cheat-sheet/index.md
The removed statement is already executed in Enlight_Controller_Plugins_Json_Bootstrap::setRenderer() (engine/Library/Enlight/Controller/Plugins/Json/Bootstrap.php::172 in SW 5.4) and therefore obsolete
=> Remove unnecessary line

source/developers-guide/plugin-quick-start/index.md
This adds a few hints about how plugins
must be named and placed in order to
correctly be picked up by the Shopware
plugin initializer.
=> [TASK] Improve plugin naming directions

source/developers-guide/http-cache/index.md
Describe settings to set, when using build-in http cache in a cluster environment. This is needed for correct cache invalidation. I have an article on my mind, were different varnish and shopware http cache scenarios are described. I would link that in the section but i couldn't find it any more. Do anybody remember this article, too?
=> describe cache purging in cluster env

source/developers-guide/rest-api/examples/article/index.md
The active = true flag of the mainDetail is essential because otherwise the article will show up as active in the backend but not in the frontend.
=> Add some active flags

source/developers-guide/rest-api/models/index.md
Like article there is no model summary on this page but a dedicated page. Order has no summary on this page either but is linked as one.
=> Linked order to the dedicated order page

source/developers-guide/plugin-quick-start/index.md
Looking at `$context->scheduleClearCache(...Context::CACHE_LIST_ALL);` I thought `scheduleClearCache` takes a variable number of arguments instead of an array. This commit clears that up
=> InstallContext instead of ...Context

source/sysadmins-guide/varnish-setup/index.md
this is similar to Shopwares `ignored_url_parameters`, then inspired by PR [#1159](https://github.com/shopware/shopware/pull/1195) and introduced in [SW-19263](https://github.com/shopware/shopware/commit/fae510cd5d50d0bb0d5dad4ed5daf9bd5fa5b345) to improve the cache hit rate. It uses a minimal set of tags and is intended to provide a stub for varnish users to check their own backend request logs and a place in the vcl to insert them. The second regex matches leftover trailing "?" and/or "&" symbols
=> Add marketing tag removal to varnish vcl config

source/developers-guide/plugin-quick-start/index.md
As I ran into an issue that customized cronjobs intervals where set back on a plugin update I searched for the reason, found it and now writing a hint for the documentation so anyone who will discover the `cronjob.xml` for their first time will have some "behind the scenes" knowledge about it.
=> Added hints about the cronjob.xml

source/developers-guide/coding-standards/index.md
I updated the php-cs-fixer call because the option "level" doesn't exist and the general `.php_cs.dist` should be considered.
=> Update php-cs-fixer call

source/designers-guide/custom-listing-page/index.md
Property-value relationship in unitze mixin is defined as `@{property}: ~"@{pxValue}px"`. So the `px` ending in mixin causes  an invalid value.
=> Fix value of unitize mixin property

source/developers-guide/shopware-5-plugin-update-guide/index.md
With the new plugin system the question if user data should be removed will always be asked. It is not optional anymore and cannot be invoked manually.
=> Updates info about uninstalling a plugin

source/sysadmins-guide/varnish-setup/index.md
This pull request updates the Varnish configuration, so that the /checkout and /account endpoints are passed through varnish without caching. This change allows multiple requests to these endpoints to run in parallel.
Varnish makes sure that only one request per URL is in flight for backend fetches. This allows to answer all requests to one URL as soon as the first request is successful. But this only works if the request can be cached. For URLs that can not be cached it limits the requests to each unique URL to one in flight request. By passing varnish for these URLs, more than one request can run in parallel to these endpoints.
=> Varnish config: Pass checkout and account paths directly to php

source/assets/css/_imports/codeExpand.less
Only on collapsed code there is a margin on top resulting in ugly jumping of code block.
=> Removed margin-top from .code-collapsed

source/sysadmins-guide/elasticsearch-setup/index.md
The example won't work because of a syntax error.
=> Fix wrong config example

components.html
It was weird to neither have a preview nor a code example. The reference to the jquery ui page said: `$('input').datepicker();` which was not working in shopware and is therfore confusing. As the current js files in styletile do not contain the datepicker I did not include a preview iframe but referenced the documention for an approach that is a bit more clear.
=> Added reference to existing datepicker documentation

source/designers-guide/smarty/index.md
One of our apprentices noticed an error while working through the documentation :smirk: The given example will output nothing and confuses newbies.
I am not sure about the post about the seo engine that might have the same issue: https://github.com/shopware/devdocs/blob/93cb1789f9b93acf88d82d545ae0883d21e892eb/source/blog/_posts/2015-08-11-seo-engine.md#configuring-the-urls
There it also uses `sArticle.name` 
> `{sCategoryPath articleID=$sArticle.id}/{$sArticle.id}/{$sArticle.name}`
=> Using a working example to display a product name

source/developers-guide/rest-api/api-resource-article/index.md
See: https://github.com/shopware/shopware/blob/5.5/engine/Shopware/Components/Api/Resource/Article.php#L221-L226
The filter ?language uses the shopID, not a locale. Since translation of entities are based on the shop, not a locale, it won't make any sence to use the locale here. Further the locale is not a unique alias, since more than one shop can have the locale en_GB.
=> Fix wrong filter description in rest api

source/developers-guide/custom-shopping-world-elements/index.md
To avoid confusion, it should be good to mention the data appearing under 
$Data.key instead of $key directly.
=> Explicitly mention $Data

source/developers-guide/plugin-lastregistrations-widget/index.md
As this seems to be a :clipboard: :ramen: guide the files should contain out of the box correct content to make it easier to get started with ext js. The first line in the included files should be added with useless statements or smarty statements as in the compiled main.js this line is commented out.
If this first line is missing invalid javascript is generated.
=> Added missing first line to build the javascript correctly

source/developers-guide/plugin-lastregistrations-widget/index.md
The guide is quite detailed. The demand on snippets for the extjs view and their namespaces can be extrapolated by reading the code of the extjs view. But there is no hint to add a snippet to the widget labels to display correctly in the "widget add" dropdown.
=> Added hint to add snippets

source/developers-guide/event-guide/index.md
The event types `notify` example has a syntax error
```
$this->container->get('events')->notify(
'SwagEvent_Controller_notifyAction',
[
'payload' => 123,
'payload2' => 'more Payload'    // <- Missing comma
'yourPayload' => 'LoremIpsum' 
]
);
```
=> Fixing syntax error in events payload examples

source/developers-guide/plugin-quick-start/index.md
-missing class "SloganPrinter" added in the docs
-wrong smarty variablenames fixed
Signed-off-by: cedrix <kassierer@cedrix.com>
=> XCONY - added missing class and fixed smarty-variables

source/developers-guide/rest-api/models/index.md
The payment status link on https://developers.shopware.com/developers-guide/rest-api/api-resource-orders/ leads to nothing so i added the payment status model.
I also fixed the column "description" to "name" as this is the naming in the api result.
=> Added payment status

source/_partials/api_badge.twig, source/assets/css/_imports/api-badge.less, source/assets/css/basic.less, source/developers-guide/plugin-guidelines/index.md, source/developers-guide/rest-api/api-resource-cache/index.md, source/developers-guide/rest-api/api-resource-user/index.md, source/developers-guide/rest-api/customer-streams/index.md, source/developers-guide/rest-api/examples/article/index.md, source/developers-guide/rest-api/examples/batch/index.md, source/developers-guide/rest-api/examples/cache/index.md, source/developers-guide/rest-api/examples/category/index.md, source/developers-guide/rest-api/examples/customer/index.md, source/developers-guide/rest-api/examples/filter/index.md, source/developers-guide/rest-api/examples/media/index.md, source/developers-guide/rest-api/examples/merge-mode/index.md, source/developers-guide/rest-api/examples/order/index.md, source/developers-guide/rest-api/examples/payment/index.md, source/developers-guide/rest-api/examples/translation/index.md, source/developers-guide/rest-api/index.md, source/developers-guide/rest-api/plugin-api-extension/index.md
Like described in the title - I rewrote all examples from using the example-client written in PHP to JSON. This means the examples can now be copied and executed with any HTTP-Client.
Instead of showing the method to be used via function calls `$client->post()`, they're now displayed using a colour-coded badge.
There are two issues still left to be discussed I think:
1. Should the example client still be documented? (I left it as it is)
2. There are a few pages which show `GET` requests [with request-bodies](https://developers.shopware.com/developers-guide/rest-api/customer-streams/#get-information-about-an-existing-stream) and I didn't rewrite those, as I think they rely on non-standard behaviour. Should these examples be kept or deleted?
=> Rewrite API examples to JSON, add badges to represent the HTTP request method

source/developers-guide/shopware-5-cli-commands/index.md
There was a documention missing for the completion feature introduced here:
https://github.com/shopware/shopware/pull/1488
https://github.com/shopware/shopware/pull/2097
=> Add documentation for completion

source/_layouts/default.twig.html, source/_layouts/start.twig.html, source/assets/css/basic.less
This change restructures the left side menu, so that all existing links are bundled under a `Shopware 5` section (open by default). Another section `Shopware 6` with a corresponding link is added as well.
=> SW-25273 - Add a link to the Shopware 6 documentation

exampleplugins/5.2/SwagController/Resources/services.xml, exampleplugins/5.2/SwagController/Subscriber/TemplateRegistration.php
Wrong namespace is used in the SwagController example
=> Fix broken SwagController example plugin

source/developers-guide/rest-api/api-resource-article/index.md, source/developers-guide/rest-api/models/index.md
I don't want to be a shitty hacktoberfest developer but this is something i stumbled upon this day 😄 
The field "name" is not used in this context - the source code revealed that it should be "number".
=> Fix article related and similar column

source/developers-guide/elasticsearch/index.md
corrected doc for addressing of newly created mapping for elastic search, as the properties attributes have to be ignored when addressing the field
I had massive problems to address attributes created over the free text management inside the elastic search queries generated by using the ONGR Framework.
I noticed, that this .properties is too much. It's an attribute inside the mapping, but it does not work to address the field with it. By addressing it has to be removed.
=> corrected doc for elastic search

source/sysadmins-guide/system-requirements/index.md
This has come up in various support requests, where orders with many items couldn't be submitted due to this setting being lower than `16M`.
=> Extend recommended MySQL settings

source/developers-guide/rest-api/models/index.md
The data type of the shipped value is wrong in the developers documentation.
The data type should be integer:
https://github.com/shopware/shopware/blob/c8558e5da009b1b608d77f1decff6484bbe52cf0/engine/Shopware/Models/Order/Detail.php#L206-L211
=> Update `shipped` data type

source/sysadmins-guide/installation-guide/index.md
Just about to install Shopware 5 for the first time when I stumbled upon these dead links in the docs. Found some working ones that might be a better fit.
Download from git release page: https://github.com/shopware5/shopware/releases
Installation instructions: https://docs.shopware.com/en/shopware-5-en/first-steps/installing-shopware?category=shopware-5-en/getting-started
Also the current official download page doesn't have Shopware 5 anymore, so the install guide should get updated as well:
=> fix: broken download and install guide links
